version: "3.9"

networks:
  my_net:
    ipam:
      driver: default
      config:
        - subnet: "172.0.0.0/24"

services:
  my_mysql:
    image: "mysql:8"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    restart: unless-stopped
    networks:
      my_net:
        ipv4_address: 172.0.0.2
