version: "3.9"

networks:
  my_net:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

services:
  my_mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASS
    restart: unless-stopped
    networks:
      my_net:
        ipv4_address: 172.18.0.2
    volumes:
      - type: bind
        source: $MYSQL_CONF_PATH
        target: /etc/mysql/conf.d
        read_only: true
  my_redis:
    image: redis:7
    command: [ redis-server, /usr/local/etc/redis/redis.conf ]
    restart: unless-stopped
    networks:
      my_net:
        ipv4_address: 172.18.0.3
    volumes:
      - type: bind
        source: $REDIS_CONF_PATH
        target: /usr/local/etc/redis
        read_only: true
  my_rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    networks:
      my_net:
        ipv4_address: 172.18.0.4